---
title: "visualization_1"
author: "Xinyi Lin"
date: "9/27/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)       #????????what is this package for
```

Here is a illustration of rnoaa
```{r}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## start making plots

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
weather_df %>%
  filter(name == "CentralPark_NY") %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

## More plot options

Add an aesthetic

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

add a geom

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)    # se represent of standard error, I guess.
```

add some options ...

add a geom

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.4) +    # make points more transperancy 
  geom_smooth(se = FALSE)    # se represent of standard error, I guess.
```

changing the place of "color"

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +    # make points more transperancy 
  geom_smooth(se = FALSE)    # se represent of standard error, I guess.
```

facetting...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +    # make points more transperancy 
  geom_smooth(se = FALSE) +   # se represent of standard error, I guess.
  facet_grid( ~ name)      # seperate to three pictures 
```

a more interesting plot

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, color = name, size = prcp)) +
  geom_point() +
  geom_smooth(se = FALSE) + 
  facet_grid( ~ name)
```

something interesting

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))  # ggplot will find a variable name "blue", but it is not exist, so ggplot will create a variable name "blue", but might not be a blue one.
```

hist

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram()
```

not easy to read so turn to density function

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5) 
```

test of adjust

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4)   # without adjust the curve become more smooth
```

boxplot

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_boxplot()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin()
```

saving the plot



